name: Deploy on PR Merge

on:
  workflow_dispatch: {}
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'index.html'
      - 'package.json'
      - 'src/**'
      - 'vite.config.ts'
      - 'vitest.config.ts'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.FIREBASE_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.CONTAINER_BUILD_SERVICE_ACCOUNT }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@2028e2d7d30a78c6910e0632e48dd561b064884d #v3
        with:
          service: ${{ vars.SERVICE_NAME }}
          region: ${{ vars.GCP_LOCATION }}
          skip_default_labels: true
          image: us-east4-docker.pkg.dev/leoy-devrel-apps/apps/api-keys-spa@sha256:ec3f70647d1f6cf9f28f09310db66faa2d6f797f317a4340c0ad2ff1873ec56a
          flags: "--no-allow-unauthenticated --ingress=internal-and-cloud-load-balancing --cpu-boost --service-account=${{ secrets.CLOUD_RUN_APP_SERVICE_NAME }}"
